author_approval: required
approve_by_comment: true
approve_regex: '^(Approved|:\+1:)'
reject_regex: '^(Rejected|:\-1:)'
reset_on_push: true
reviewers:
  members:
  - mustafaersahin
  - tunix
  - lihorecoco
  name: default
  required: 1
