language: node_js
node_js:
    - "5"
before_script:
    - npm install -g gulp
sudo: required
services:
    - docker
script:
    - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && gulp || true'
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && gulp docker || true'
