language: node_js
node_js:
    - "5"
before_script:
    - npm install -g gulp
script: gulp
sudo: required
services:
    - docker
after_success:
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker build -t "$DOCKER_IMAGE_NAME" . || false'
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || false'
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push "$DOCKER_IMAGE_NAME" || false'
